language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

script:
  - ./gradlew test
  - ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.package=com.responsivebytes.gradeconverter.main
