language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.0
    - android-28

script: ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.package=com.responsivebytes.gradeconverter.main
