language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

before_install:
  - echo yes | sdkmanager tools
  - echo yes | sdkmanager "system-images;android-24;default;armeabi-v7a"
  - echo no | android create avd --force -n test -k "system-images;android-24;default;armeabi-v7a" -c 128M
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

before_script:
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
	- adb shell settings put global transition_animation_scale 0 &
	- adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew test
  - ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.package=com.responsivebytes.gradeconverter.main
